version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            -   |
                #Install dependenciest
                npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run-script build
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Run some tests here (todo)
            - echo Tests completed on `date`
artifacts:
    files:
        - 'dist/**/*'
    name: myname-$(date +%Y-%m-%d)